FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3001

RUN addgroup -S nodejs -g 1001 && \
    adduser -S nodejs -u 1001

COPY package*.json ./

RUN npm ci --omit=dev

COPY --chown=nodejs:nodejs . .

USER nodejs

EXPOSE 3001

CMD ["npm", "start"]