pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        IMAGE_NAME = "msob7/go-app:latest"
    }

    stages {
        stage('Docker Login') {
            steps {
                sh '''
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login \
                  -u $DOCKERHUB_CREDENTIALS_USR \
                  --password-stdin
                '''
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                cd project2/go-app
                docker build -t $IMAGE_NAME -f dockerfile-prod .
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME
                '''
            }
        }
    }
}
