pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('Dockerhub')
        IMAGE_NAME = "sob7/go-app"
        DOCKER_SERVER = "10.100.77.53"
        DOCKER_USER = "msobh"
        CONTAINER_NAME = "my-goapp"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Login') {
            steps {
                sh '''
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login \
                -u $DOCKERHUB_CREDENTIALS_USR \
                --password-stdin
                '''
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                cd project2/go-app

                docker build \
                    -t $IMAGE_NAME:latest \
                    -t $IMAGE_NAME:${BUILD_NUMBER} \
                    -f Dockerfile-prod .
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:${BUILD_NUMBER}
                '''
            }
        }

        stage('Deploy to Docker Server') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ${DOCKER_USER}@${DOCKER_SERVER} '
                    docker pull ${IMAGE_NAME}:latest

                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true

                    docker run -d \
                        --name ${CONTAINER_NAME} \
                        --restart unless-stopped \
                        -p 8080:8080 \
                        ${IMAGE_NAME}:latest
                '
                """
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                sleep 10
                curl http://10.100.77.53:8080/health
                '''
            }
        }

    }

    post {

        success {
            echo '================================='
            echo 'Pipeline completed successfully!'
            echo "Image: ${IMAGE_NAME}:${BUILD_NUMBER}"
            echo '================================='
        }

        failure {
            echo 'Pipeline Failed!'
        }

        always {
            cleanWs()
        }
    }
}
