version: "3"
services:
  mysql_database:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tk-db  # safer name, no hyphen
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: tk-db
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    depends_on:
      - mysql_database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5000"
    environment:
      PMA_HOST: mysql_database
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql: {}
