pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "myapp"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify') {
            steps {
                sh 'docker --version'
                sh 'docker compose version'
            }
        }

        stage('Build Images') {
            steps {
                dir('p1') {
                    sh 'docker compose build'
                }
            }
        }

        stage('Start Containers') {
            steps {
                dir('p1') {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Health Check') {
            steps {
                dir('p1') {
                    sh 'docker ps'
                    sh 'docker compose ps'
                }
            }
        }
    }

    post {
        always {
            dir('p1') {
                sh 'docker compose ps'
            }
        }

        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}